// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Application
type Application struct {
	ID              string    `json:"id"`
	Description     OptString `json:"description"`
	DisplayID       string    `json:"display_id"`
	RepositoryURL   string    `json:"repository_url"`
	AppconfigPath   string    `json:"appconfig_path"`
	AppconfigBranch string    `json:"appconfig_branch"`
}

// GetID returns the value of ID.
func (s *Application) GetID() string {
	return s.ID
}

// GetDescription returns the value of Description.
func (s *Application) GetDescription() OptString {
	return s.Description
}

// GetDisplayID returns the value of DisplayID.
func (s *Application) GetDisplayID() string {
	return s.DisplayID
}

// GetRepositoryURL returns the value of RepositoryURL.
func (s *Application) GetRepositoryURL() string {
	return s.RepositoryURL
}

// GetAppconfigPath returns the value of AppconfigPath.
func (s *Application) GetAppconfigPath() string {
	return s.AppconfigPath
}

// GetAppconfigBranch returns the value of AppconfigBranch.
func (s *Application) GetAppconfigBranch() string {
	return s.AppconfigBranch
}

// SetID sets the value of ID.
func (s *Application) SetID(val string) {
	s.ID = val
}

// SetDescription sets the value of Description.
func (s *Application) SetDescription(val OptString) {
	s.Description = val
}

// SetDisplayID sets the value of DisplayID.
func (s *Application) SetDisplayID(val string) {
	s.DisplayID = val
}

// SetRepositoryURL sets the value of RepositoryURL.
func (s *Application) SetRepositoryURL(val string) {
	s.RepositoryURL = val
}

// SetAppconfigPath sets the value of AppconfigPath.
func (s *Application) SetAppconfigPath(val string) {
	s.AppconfigPath = val
}

// SetAppconfigBranch sets the value of AppconfigBranch.
func (s *Application) SetAppconfigBranch(val string) {
	s.AppconfigBranch = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/HealthCheckStatus
type HealthCheckStatus struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthCheckStatus) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthCheckStatus) SetStatus(val string) {
	s.Status = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
