// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateApplication implements CreateApplication operation.
//
// アプリケーションを作成するAPI.
//
// POST /v1alpha1/applications
func (UnimplementedHandler) CreateApplication(ctx context.Context, req *CreateApplicationRequest) (r *Application, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApplicationSecret implements CreateApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを作成するAPI.
//
// POST /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) CreateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params CreateApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApplication implements DeleteApplication operation.
//
// 特定のアプリケーションを削除するAPI.
//
// DELETE /v1alpha1/applications/{name}
func (UnimplementedHandler) DeleteApplication(ctx context.Context, params DeleteApplicationParams) (r DeleteApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApplicationSecret implements DeleteApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを削除するAPI.
//
// DELETE /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) DeleteApplicationSecret(ctx context.Context, params DeleteApplicationSecretParams) (r DeleteApplicationSecretRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplication implements GetApplication operation.
//
// 特定のアプリケーションを取得するAPI.
//
// GET /v1alpha1/applications/{name}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r *Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationLogs implements GetApplicationLogs operation.
//
// 特定のアプリケーションのPodログを取得するAPI.
//
// GET /v1alpha1/applications/{name}/logs
func (UnimplementedHandler) GetApplicationLogs(ctx context.Context, params GetApplicationLogsParams) (r GetApplicationLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationReleases implements GetApplicationReleases operation.
//
// 特定のアプリケーションのリリース一覧を取得するAPI.
//
// GET /v1alpha1/applications/{name}/releases
func (UnimplementedHandler) GetApplicationReleases(ctx context.Context, params GetApplicationReleasesParams) (r GetApplicationReleasesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationSecret implements GetApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを取得するAPI.
//
// GET /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) GetApplicationSecret(ctx context.Context, params GetApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplications implements GetApplications operation.
//
// アプリケーション一覧を取得するAPI.
//
// GET /v1alpha1/applications
func (UnimplementedHandler) GetApplications(ctx context.Context) (r []Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCSRFToken implements GetCSRFToken operation.
//
// CSRFトークンを取得するAPI。セッションCookie認証が必要。.
//
// GET /auth/csrf-token
func (UnimplementedHandler) GetCSRFToken(ctx context.Context) (r *CSRFTokenResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthLiveness implements GetHealthLiveness operation.
//
// Liveness statusを取得するAPI.
//
// GET /health/liveness
func (UnimplementedHandler) GetHealthLiveness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthReadiness implements GetHealthReadiness operation.
//
// Readiness statusを取得するAPI.
//
// GET /health/readiness
func (UnimplementedHandler) GetHealthReadiness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GitHubOAuthCallback implements GitHubOAuthCallback operation.
//
// GitHub OAuthコールバック処理API.
//
// GET /auth/github/callback
func (UnimplementedHandler) GitHubOAuthCallback(ctx context.Context, params GitHubOAuthCallbackParams) (r GitHubOAuthCallbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GitHubOAuthLogin implements GitHubOAuthLogin operation.
//
// GitHub OAuthログインを開始するAPI.
//
// GET /auth/github/login
func (UnimplementedHandler) GitHubOAuthLogin(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Logout implements Logout operation.
//
// ログアウト処理API.
//
// POST /auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) (r *LogoutOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshToken implements RefreshToken operation.
//
// JWT リフレッシュ処理API.
//
// POST /auth/refresh
func (UnimplementedHandler) RefreshToken(ctx context.Context, req *RefreshTokenReq) (r RefreshTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RollbackApplication implements RollbackApplication operation.
//
// 特定のアプリケーションを指定したリリースにロールバックするAPI.
//
// POST /v1alpha1/applications/{name}/rollback
func (UnimplementedHandler) RollbackApplication(ctx context.Context, req *RollbackRequest, params RollbackApplicationParams) (r RollbackApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplication implements UpdateApplication operation.
//
// 特定のアプリケーションを更新するAPI.
//
// PUT /v1alpha1/applications/{name}
func (UnimplementedHandler) UpdateApplication(ctx context.Context, req *UpdateApplicationRequest, params UpdateApplicationParams) (r UpdateApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplicationSecret implements UpdateApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを更新するAPI.
//
// PUT /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) UpdateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params UpdateApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
