// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateApplicationOperation       OperationName = "CreateApplication"
	CreateApplicationSecretOperation OperationName = "CreateApplicationSecret"
	GetApplicationOperation          OperationName = "GetApplication"
	GetApplicationSecretOperation    OperationName = "GetApplicationSecret"
	GetApplicationsOperation         OperationName = "GetApplications"
	GetHealthLivenessOperation       OperationName = "GetHealthLiveness"
	GetHealthReadinessOperation      OperationName = "GetHealthReadiness"
	UpdateApplicationSecretOperation OperationName = "UpdateApplicationSecret"
)
