// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateApplication implements CreateApplication operation.
	//
	// アプリケーションを作成するAPI.
	//
	// POST /v1alpha1/applications
	CreateApplication(ctx context.Context, req *CreateApplicationRequest) (*Application, error)
	// GetApplication implements GetApplication operation.
	//
	// 特定のアプリケーションを取得するAPI.
	//
	// GET /v1alpha1/applications/{name}
	GetApplication(ctx context.Context, params GetApplicationParams) (*Application, error)
	// GetApplications implements GetApplications operation.
	//
	// アプリケーション一覧を取得するAPI.
	//
	// GET /v1alpha1/applications
	GetApplications(ctx context.Context) ([]Application, error)
	// GetHealthLiveness implements GetHealthLiveness operation.
	//
	// Liveness statusを取得するAPI.
	//
	// GET /health/liveness
	GetHealthLiveness(ctx context.Context) (*HealthCheckStatus, error)
	// GetHealthReadiness implements GetHealthReadiness operation.
	//
	// Readiness statusを取得するAPI.
	//
	// GET /health/readiness
	GetHealthReadiness(ctx context.Context) (*HealthCheckStatus, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
