// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Application
type Application struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Description     OptString `json:"description"`
	DisplayID       string    `json:"display_id"`
	RepositoryURL   string    `json:"repository_url"`
	AppconfigPath   string    `json:"appconfig_path"`
	AppconfigBranch string    `json:"appconfig_branch"`
}

// GetID returns the value of ID.
func (s *Application) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Application) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Application) GetDescription() OptString {
	return s.Description
}

// GetDisplayID returns the value of DisplayID.
func (s *Application) GetDisplayID() string {
	return s.DisplayID
}

// GetRepositoryURL returns the value of RepositoryURL.
func (s *Application) GetRepositoryURL() string {
	return s.RepositoryURL
}

// GetAppconfigPath returns the value of AppconfigPath.
func (s *Application) GetAppconfigPath() string {
	return s.AppconfigPath
}

// GetAppconfigBranch returns the value of AppconfigBranch.
func (s *Application) GetAppconfigBranch() string {
	return s.AppconfigBranch
}

// SetID sets the value of ID.
func (s *Application) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Application) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Application) SetDescription(val OptString) {
	s.Description = val
}

// SetDisplayID sets the value of DisplayID.
func (s *Application) SetDisplayID(val string) {
	s.DisplayID = val
}

// SetRepositoryURL sets the value of RepositoryURL.
func (s *Application) SetRepositoryURL(val string) {
	s.RepositoryURL = val
}

// SetAppconfigPath sets the value of AppconfigPath.
func (s *Application) SetAppconfigPath(val string) {
	s.AppconfigPath = val
}

// SetAppconfigBranch sets the value of AppconfigBranch.
func (s *Application) SetAppconfigBranch(val string) {
	s.AppconfigBranch = val
}

func (*Application) rollbackApplicationRes() {}
func (*Application) updateApplicationRes()   {}

// Ref: #/components/schemas/ApplicationLogs
type ApplicationLogs struct {
	ApplicationName string   `json:"application_name"`
	PodLogs         []PodLog `json:"pod_logs"`
}

// GetApplicationName returns the value of ApplicationName.
func (s *ApplicationLogs) GetApplicationName() string {
	return s.ApplicationName
}

// GetPodLogs returns the value of PodLogs.
func (s *ApplicationLogs) GetPodLogs() []PodLog {
	return s.PodLogs
}

// SetApplicationName sets the value of ApplicationName.
func (s *ApplicationLogs) SetApplicationName(val string) {
	s.ApplicationName = val
}

// SetPodLogs sets the value of PodLogs.
func (s *ApplicationLogs) SetPodLogs(val []PodLog) {
	s.PodLogs = val
}

func (*ApplicationLogs) getApplicationLogsRes() {}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	Success   bool      `json:"success"`
	User      User      `json:"user"`
	ExpiresAt time.Time `json:"expires_at"`
}

// GetSuccess returns the value of Success.
func (s *AuthResponse) GetSuccess() bool {
	return s.Success
}

// GetUser returns the value of User.
func (s *AuthResponse) GetUser() User {
	return s.User
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *AuthResponse) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetSuccess sets the value of Success.
func (s *AuthResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetUser sets the value of User.
func (s *AuthResponse) SetUser(val User) {
	s.User = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *AuthResponse) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

func (*AuthResponse) gitHubOAuthCallbackRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CSRFTokenResponse
type CSRFTokenResponse struct {
	CsrfToken string `json:"csrf_token"`
}

// GetCsrfToken returns the value of CsrfToken.
func (s *CSRFTokenResponse) GetCsrfToken() string {
	return s.CsrfToken
}

// SetCsrfToken sets the value of CsrfToken.
func (s *CSRFTokenResponse) SetCsrfToken(val string) {
	s.CsrfToken = val
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreateApplicationRequest
type CreateApplicationRequest struct {
	Name            string    `json:"name"`
	Description     OptString `json:"description"`
	RepositoryURL   string    `json:"repository_url"`
	AppconfigPath   string    `json:"appconfig_path"`
	AppconfigBranch string    `json:"appconfig_branch"`
}

// GetName returns the value of Name.
func (s *CreateApplicationRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateApplicationRequest) GetDescription() OptString {
	return s.Description
}

// GetRepositoryURL returns the value of RepositoryURL.
func (s *CreateApplicationRequest) GetRepositoryURL() string {
	return s.RepositoryURL
}

// GetAppconfigPath returns the value of AppconfigPath.
func (s *CreateApplicationRequest) GetAppconfigPath() string {
	return s.AppconfigPath
}

// GetAppconfigBranch returns the value of AppconfigBranch.
func (s *CreateApplicationRequest) GetAppconfigBranch() string {
	return s.AppconfigBranch
}

// SetName sets the value of Name.
func (s *CreateApplicationRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateApplicationRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetRepositoryURL sets the value of RepositoryURL.
func (s *CreateApplicationRequest) SetRepositoryURL(val string) {
	s.RepositoryURL = val
}

// SetAppconfigPath sets the value of AppconfigPath.
func (s *CreateApplicationRequest) SetAppconfigPath(val string) {
	s.AppconfigPath = val
}

// SetAppconfigBranch sets the value of AppconfigBranch.
func (s *CreateApplicationRequest) SetAppconfigBranch(val string) {
	s.AppconfigBranch = val
}

// Ref: #/components/schemas/CreateSecretRequest
type CreateSecretRequest struct {
	Items []SecretItem `json:"items"`
}

// GetItems returns the value of Items.
func (s *CreateSecretRequest) GetItems() []SecretItem {
	return s.Items
}

// SetItems sets the value of Items.
func (s *CreateSecretRequest) SetItems(val []SecretItem) {
	s.Items = val
}

// DeleteApplicationNoContent is response for DeleteApplication operation.
type DeleteApplicationNoContent struct{}

func (*DeleteApplicationNoContent) deleteApplicationRes() {}

// DeleteApplicationSecretNoContent is response for DeleteApplicationSecret operation.
type DeleteApplicationSecretNoContent struct{}

func (*DeleteApplicationSecretNoContent) deleteApplicationSecretRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) deleteApplicationRes()       {}
func (*Error) deleteApplicationSecretRes() {}
func (*Error) gitHubOAuthCallbackRes()     {}
func (*Error) refreshTokenRes()            {}
func (*Error) updateApplicationRes()       {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetApplicationLogsNotFound Error

func (*GetApplicationLogsNotFound) getApplicationLogsRes() {}

type GetApplicationLogsServiceUnavailable Error

func (*GetApplicationLogsServiceUnavailable) getApplicationLogsRes() {}

type GetApplicationReleasesNotFound Error

func (*GetApplicationReleasesNotFound) getApplicationReleasesRes() {}

type GetApplicationReleasesOKApplicationJSON []Release

func (*GetApplicationReleasesOKApplicationJSON) getApplicationReleasesRes() {}

type GetApplicationReleasesServiceUnavailable Error

func (*GetApplicationReleasesServiceUnavailable) getApplicationReleasesRes() {}

// GitHubOAuthLoginFound is response for GitHubOAuthLogin operation.
type GitHubOAuthLoginFound struct{}

// Ref: #/components/schemas/HealthCheckStatus
type HealthCheckStatus struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthCheckStatus) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthCheckStatus) SetStatus(val string) {
	s.Status = val
}

type LogoutOK struct {
	Success bool `json:"success"`
}

// GetSuccess returns the value of Success.
func (s *LogoutOK) GetSuccess() bool {
	return s.Success
}

// SetSuccess sets the value of Success.
func (s *LogoutOK) SetSuccess(val bool) {
	s.Success = val
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PodLog
type PodLog struct {
	PodName       string `json:"pod_name"`
	ContainerName string `json:"container_name"`
	Logs          string `json:"logs"`
}

// GetPodName returns the value of PodName.
func (s *PodLog) GetPodName() string {
	return s.PodName
}

// GetContainerName returns the value of ContainerName.
func (s *PodLog) GetContainerName() string {
	return s.ContainerName
}

// GetLogs returns the value of Logs.
func (s *PodLog) GetLogs() string {
	return s.Logs
}

// SetPodName sets the value of PodName.
func (s *PodLog) SetPodName(val string) {
	s.PodName = val
}

// SetContainerName sets the value of ContainerName.
func (s *PodLog) SetContainerName(val string) {
	s.ContainerName = val
}

// SetLogs sets the value of Logs.
func (s *PodLog) SetLogs(val string) {
	s.Logs = val
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshTokenReq) GetRefreshToken() string {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshTokenReq) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/Release
type Release struct {
	Name            string    `json:"name"`
	Commit          OptString `json:"commit"`
	State           string    `json:"state"`
	RepositoryURL   string    `json:"repository_url"`
	AppconfigPath   string    `json:"appconfig_path"`
	AppconfigBranch string    `json:"appconfig_branch"`
	CreatedAt       time.Time `json:"created_at"`
}

// GetName returns the value of Name.
func (s *Release) GetName() string {
	return s.Name
}

// GetCommit returns the value of Commit.
func (s *Release) GetCommit() OptString {
	return s.Commit
}

// GetState returns the value of State.
func (s *Release) GetState() string {
	return s.State
}

// GetRepositoryURL returns the value of RepositoryURL.
func (s *Release) GetRepositoryURL() string {
	return s.RepositoryURL
}

// GetAppconfigPath returns the value of AppconfigPath.
func (s *Release) GetAppconfigPath() string {
	return s.AppconfigPath
}

// GetAppconfigBranch returns the value of AppconfigBranch.
func (s *Release) GetAppconfigBranch() string {
	return s.AppconfigBranch
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Release) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetName sets the value of Name.
func (s *Release) SetName(val string) {
	s.Name = val
}

// SetCommit sets the value of Commit.
func (s *Release) SetCommit(val OptString) {
	s.Commit = val
}

// SetState sets the value of State.
func (s *Release) SetState(val string) {
	s.State = val
}

// SetRepositoryURL sets the value of RepositoryURL.
func (s *Release) SetRepositoryURL(val string) {
	s.RepositoryURL = val
}

// SetAppconfigPath sets the value of AppconfigPath.
func (s *Release) SetAppconfigPath(val string) {
	s.AppconfigPath = val
}

// SetAppconfigBranch sets the value of AppconfigBranch.
func (s *Release) SetAppconfigBranch(val string) {
	s.AppconfigBranch = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Release) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

type RollbackApplicationNotFound Error

func (*RollbackApplicationNotFound) rollbackApplicationRes() {}

type RollbackApplicationServiceUnavailable Error

func (*RollbackApplicationServiceUnavailable) rollbackApplicationRes() {}

// Ref: #/components/schemas/RollbackRequest
type RollbackRequest struct {
	ReleaseName string `json:"release_name"`
}

// GetReleaseName returns the value of ReleaseName.
func (s *RollbackRequest) GetReleaseName() string {
	return s.ReleaseName
}

// SetReleaseName sets the value of ReleaseName.
func (s *RollbackRequest) SetReleaseName(val string) {
	s.ReleaseName = val
}

// Ref: #/components/schemas/Secret
type Secret struct {
	ID    string       `json:"id"`
	Items []SecretItem `json:"items"`
}

// GetID returns the value of ID.
func (s *Secret) GetID() string {
	return s.ID
}

// GetItems returns the value of Items.
func (s *Secret) GetItems() []SecretItem {
	return s.Items
}

// SetID sets the value of ID.
func (s *Secret) SetID(val string) {
	s.ID = val
}

// SetItems sets the value of Items.
func (s *Secret) SetItems(val []SecretItem) {
	s.Items = val
}

// Ref: #/components/schemas/SecretItem
type SecretItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns the value of Key.
func (s *SecretItem) GetKey() string {
	return s.Key
}

// GetValue returns the value of Value.
func (s *SecretItem) GetValue() string {
	return s.Value
}

// SetKey sets the value of Key.
func (s *SecretItem) SetKey(val string) {
	s.Key = val
}

// SetValue sets the value of Value.
func (s *SecretItem) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/TokenPair
type TokenPair struct {
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPair) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPair) GetRefreshToken() string {
	return s.RefreshToken
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *TokenPair) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPair) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPair) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *TokenPair) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

func (*TokenPair) refreshTokenRes() {}

// Ref: #/components/schemas/UpdateApplicationRequest
type UpdateApplicationRequest struct {
	RepositoryURL   string `json:"repository_url"`
	AppconfigPath   string `json:"appconfig_path"`
	AppconfigBranch string `json:"appconfig_branch"`
}

// GetRepositoryURL returns the value of RepositoryURL.
func (s *UpdateApplicationRequest) GetRepositoryURL() string {
	return s.RepositoryURL
}

// GetAppconfigPath returns the value of AppconfigPath.
func (s *UpdateApplicationRequest) GetAppconfigPath() string {
	return s.AppconfigPath
}

// GetAppconfigBranch returns the value of AppconfigBranch.
func (s *UpdateApplicationRequest) GetAppconfigBranch() string {
	return s.AppconfigBranch
}

// SetRepositoryURL sets the value of RepositoryURL.
func (s *UpdateApplicationRequest) SetRepositoryURL(val string) {
	s.RepositoryURL = val
}

// SetAppconfigPath sets the value of AppconfigPath.
func (s *UpdateApplicationRequest) SetAppconfigPath(val string) {
	s.AppconfigPath = val
}

// SetAppconfigBranch sets the value of AppconfigBranch.
func (s *UpdateApplicationRequest) SetAppconfigBranch(val string) {
	s.AppconfigBranch = val
}

// Ref: #/components/schemas/User
type User struct {
	ID    string    `json:"id"`
	Login string    `json:"login"`
	Name  OptString `json:"name"`
	Email OptString `json:"email"`
	Teams []string  `json:"teams"`
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetLogin returns the value of Login.
func (s *User) GetLogin() string {
	return s.Login
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetTeams returns the value of Teams.
func (s *User) GetTeams() []string {
	return s.Teams
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetLogin sets the value of Login.
func (s *User) SetLogin(val string) {
	s.Login = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetTeams sets the value of Teams.
func (s *User) SetTeams(val []string) {
	s.Teams = val
}
