// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetApplication implements GetApplication operation.
//
// 特定のアプリケーションを取得するAPI.
//
// GET /v1alpha1/applications/{application_id}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r *Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplications implements GetApplications operation.
//
// アプリケーション一覧を取得するAPI.
//
// GET /v1alpha1/applications
func (UnimplementedHandler) GetApplications(ctx context.Context) (r []Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthLiveness implements GetHealthLiveness operation.
//
// Liveness statusを取得するAPI.
//
// GET /health/liveness
func (UnimplementedHandler) GetHealthLiveness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthReadiness implements GetHealthReadiness operation.
//
// Readiness statusを取得するAPI.
//
// GET /health/readiness
func (UnimplementedHandler) GetHealthReadiness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
