// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateApplication implements CreateApplication operation.
//
// アプリケーションを作成するAPI.
//
// POST /v1alpha1/applications
func (UnimplementedHandler) CreateApplication(ctx context.Context, req *CreateApplicationRequest) (r *Application, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApplicationSecret implements CreateApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを作成するAPI.
//
// POST /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) CreateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params CreateApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplication implements GetApplication operation.
//
// 特定のアプリケーションを取得するAPI.
//
// GET /v1alpha1/applications/{name}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r *Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationSecret implements GetApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを取得するAPI.
//
// GET /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) GetApplicationSecret(ctx context.Context, params GetApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplications implements GetApplications operation.
//
// アプリケーション一覧を取得するAPI.
//
// GET /v1alpha1/applications
func (UnimplementedHandler) GetApplications(ctx context.Context) (r []Application, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthLiveness implements GetHealthLiveness operation.
//
// Liveness statusを取得するAPI.
//
// GET /health/liveness
func (UnimplementedHandler) GetHealthLiveness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthReadiness implements GetHealthReadiness operation.
//
// Readiness statusを取得するAPI.
//
// GET /health/readiness
func (UnimplementedHandler) GetHealthReadiness(ctx context.Context) (r *HealthCheckStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplicationSecret implements UpdateApplicationSecret operation.
//
// 特定のアプリケーションのシークレットを更新するAPI.
//
// PUT /v1alpha1/applications/{name}/secret
func (UnimplementedHandler) UpdateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params UpdateApplicationSecretParams) (r *Secret, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
