// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateApplicationOperation       OperationName = "CreateApplication"
	CreateApplicationSecretOperation OperationName = "CreateApplicationSecret"
	DeleteApplicationSecretOperation OperationName = "DeleteApplicationSecret"
	GetApplicationOperation          OperationName = "GetApplication"
	GetApplicationSecretOperation    OperationName = "GetApplicationSecret"
	GetApplicationsOperation         OperationName = "GetApplications"
	GetCSRFTokenOperation            OperationName = "GetCSRFToken"
	GetHealthLivenessOperation       OperationName = "GetHealthLiveness"
	GetHealthReadinessOperation      OperationName = "GetHealthReadiness"
	GitHubOAuthCallbackOperation     OperationName = "GitHubOAuthCallback"
	GitHubOAuthLoginOperation        OperationName = "GitHubOAuthLogin"
	LogoutOperation                  OperationName = "Logout"
	RefreshTokenOperation            OperationName = "RefreshToken"
	UpdateApplicationSecretOperation OperationName = "UpdateApplicationSecret"
)
