// Code generated by ogen, DO NOT EDIT.
package api

type DeleteApplicationRes interface {
	deleteApplicationRes()
}

type DeleteApplicationSecretRes interface {
	deleteApplicationSecretRes()
}

type GetApplicationLogsRes interface {
	getApplicationLogsRes()
}

type GetApplicationReleasesRes interface {
	getApplicationReleasesRes()
}

type GitHubOAuthCallbackRes interface {
	gitHubOAuthCallbackRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type RollbackApplicationRes interface {
	rollbackApplicationRes()
}

type UpdateApplicationRes interface {
	updateApplicationRes()
}
