// Code generated by ogen, DO NOT EDIT.
package api

type DeleteApplicationSecretRes interface {
	deleteApplicationSecretRes()
}

type GitHubOAuthCallbackRes interface {
	gitHubOAuthCallbackRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}
