// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetApplicationOperation     OperationName = "GetApplication"
	GetApplicationsOperation    OperationName = "GetApplications"
	GetHealthLivenessOperation  OperationName = "GetHealthLiveness"
	GetHealthReadinessOperation OperationName = "GetHealthReadiness"
)
