// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateApplication implements CreateApplication operation.
	//
	// アプリケーションを作成するAPI.
	//
	// POST /v1alpha1/applications
	CreateApplication(ctx context.Context, req *CreateApplicationRequest) (*Application, error)
	// CreateApplicationSecret implements CreateApplicationSecret operation.
	//
	// 特定のアプリケーションのシークレットを作成するAPI.
	//
	// POST /v1alpha1/applications/{name}/secret
	CreateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params CreateApplicationSecretParams) (*Secret, error)
	// DeleteApplication implements DeleteApplication operation.
	//
	// 特定のアプリケーションを削除するAPI.
	//
	// DELETE /v1alpha1/applications/{name}
	DeleteApplication(ctx context.Context, params DeleteApplicationParams) (DeleteApplicationRes, error)
	// DeleteApplicationSecret implements DeleteApplicationSecret operation.
	//
	// 特定のアプリケーションのシークレットを削除するAPI.
	//
	// DELETE /v1alpha1/applications/{name}/secret
	DeleteApplicationSecret(ctx context.Context, params DeleteApplicationSecretParams) (DeleteApplicationSecretRes, error)
	// GetApplication implements GetApplication operation.
	//
	// 特定のアプリケーションを取得するAPI.
	//
	// GET /v1alpha1/applications/{name}
	GetApplication(ctx context.Context, params GetApplicationParams) (*Application, error)
	// GetApplicationSecret implements GetApplicationSecret operation.
	//
	// 特定のアプリケーションのシークレットを取得するAPI.
	//
	// GET /v1alpha1/applications/{name}/secret
	GetApplicationSecret(ctx context.Context, params GetApplicationSecretParams) (*Secret, error)
	// GetApplications implements GetApplications operation.
	//
	// アプリケーション一覧を取得するAPI.
	//
	// GET /v1alpha1/applications
	GetApplications(ctx context.Context) ([]Application, error)
	// GetCSRFToken implements GetCSRFToken operation.
	//
	// CSRFトークンを取得するAPI。セッションCookie認証が必要。.
	//
	// GET /auth/csrf-token
	GetCSRFToken(ctx context.Context) (*CSRFTokenResponse, error)
	// GetHealthLiveness implements GetHealthLiveness operation.
	//
	// Liveness statusを取得するAPI.
	//
	// GET /health/liveness
	GetHealthLiveness(ctx context.Context) (*HealthCheckStatus, error)
	// GetHealthReadiness implements GetHealthReadiness operation.
	//
	// Readiness statusを取得するAPI.
	//
	// GET /health/readiness
	GetHealthReadiness(ctx context.Context) (*HealthCheckStatus, error)
	// GitHubOAuthCallback implements GitHubOAuthCallback operation.
	//
	// GitHub OAuthコールバック処理API.
	//
	// GET /auth/github/callback
	GitHubOAuthCallback(ctx context.Context, params GitHubOAuthCallbackParams) (GitHubOAuthCallbackRes, error)
	// GitHubOAuthLogin implements GitHubOAuthLogin operation.
	//
	// GitHub OAuthログインを開始するAPI.
	//
	// GET /auth/github/login
	GitHubOAuthLogin(ctx context.Context) error
	// Logout implements Logout operation.
	//
	// ログアウト処理API.
	//
	// POST /auth/logout
	Logout(ctx context.Context) (*LogoutOK, error)
	// RefreshToken implements RefreshToken operation.
	//
	// JWT リフレッシュ処理API.
	//
	// POST /auth/refresh
	RefreshToken(ctx context.Context, req *RefreshTokenReq) (RefreshTokenRes, error)
	// UpdateApplicationSecret implements UpdateApplicationSecret operation.
	//
	// 特定のアプリケーションのシークレットを更新するAPI.
	//
	// PUT /v1alpha1/applications/{name}/secret
	UpdateApplicationSecret(ctx context.Context, req *CreateSecretRequest, params UpdateApplicationSecretParams) (*Secret, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
